{
 "title": "M5Stick CPlus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "External Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_temp{}", "legendFormat": " " }
   ]
  },
  {
   "title": "External Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "m5stick_temp{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_BatTemp{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "ACIN current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_Iin{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "USB vin current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_Iusb{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Battery charging current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_charge{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Battery power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_bat{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Battery output current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_disCharge{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_pressure{} / 100", "legendFormat": " " }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "m5stick_pressure{} / 100", "legendFormat": "m5stick_pressure" }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_Vaps{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_vbat{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_hum{}", "legendFormat": " " }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "m5stick_hum{}", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}